language: scala

jdk: openjdk8

scala:
  - 2.13.2

before_install:
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - nvm install node
  - nvm use node
  - nvm alias default node
  - npm install
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
  - npm test
  - sbt assembly
  - sbt docker:publishLocal

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker build -t docker.pkg.github.com/amanjpro/greenish/greenish:$TRAVIS_TAG target/docker/stage
  - echo $GITHUB_RELEASES_TOKEN | docker login https://docker.pkg.github.com -u amanjpro --password-stdin
  - docker push docker.pkg.github.com/amanjpro/greenish/greenish:$TRAVIS_TAG

deploy:
  provider: releases
  file_glob: true
  file: target/scala-2.13/greenish-assembly-*.jar
  skip_cleanup: true
  api_key: $GITHUB_RELEASES_TOKEN
  on:
    tags: true
