language: scala

jdk: openjdk8

scala:
   - 2.13.2

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport assembly

after_success:
  - export CODECOV_TOKEN="a6285401-5805-47a3-af73-6dcc4ae675c7"
  - bash <(curl -s https://codecov.io/bash)
