check-groups: {
  refresh-in-seconds: 30
  port: 8080
  env: {
    VAR1: "foo"
    VAR2: "bar"
  }
  groups: [
    {
      group-name: "Trader Delivery",
      job-entries: [
        {
          job-name: "Delivery Raw"
          check-command: "ls /tmp/delivery",
          period-pattern: "yyyy-MM-dd-HH"
          job-run-frequency: "hourly"
          timezone: "UTC"
          lookback: 24
          great-at: 0
          normal-at: 1
          warn-at: 2
          error-at: 3
        }
      ]
    },
    {
      group-name: "Trader Gateway",
      job-entries: [
        {
          job-name: "Gateway Raw"
          check-command: "ls /tmp/delivery",
          period-pattern: "yyyy-MM-dd-HH"
          job-run-frequency: "hourly"
          timezone: "UTC"
          lookback: 3
          great-at: 0
          normal-at: 1
          warn-at: 2
          error-at: 3
        }
      ]
    }
  ]
}
akka {
  refresh-dispatcher {
    type = Dispatcher
    executor = "thread-pool-executor"
    thread-pool-executor {
      fixed-pool-size = 100
    }
    throughput = 10
    mailbox-capacity = -1
  }
}
