#!/usr/bin/env bash

fst=$1

shift

for period in "$@"; do
  if ls "$GREENISH_VALUE_FOR_TEST/$fst/$period"; then
    echo -e "greenish-period\t$period\t1"
  else
    echo -e "greenish-period\t$period\t0"
  fi
done
